import type { ToolbarNames } from 'md-editor-v3'

export const EDITOR_CONFIG = {
  languageUserDefined: {
    ru: {
      toolbarTips: {
        bold: 'жирный',
        underline: 'подчёркивание',
        italic: 'курсивный',
        strikeThrough: 'перечёркнутый',
        title: 'заголовок',
        sub: 'подстрочный',
        sup: 'надстрочный',
        quote: 'цитата',
        unorderedList: 'неупорядоченный список',
        orderedList: 'упорядоченный список',
        task: 'список дел',
        codeRow: 'код в тексте',
        code: 'блок кода',
        link: 'ссылка',
        image: 'изображение',
        table: 'таблица',
        mermaid: 'граф',
        katex: 'формула',
        revoke: 'назад',
        next: 'вперёд',
        save: 'сохранить',
        prettier: 'форматировать',
        pageFullscreen: 'открыть на всю страницу',
        fullscreen: 'открыть на всю страницу',
        preview: 'превью',
        htmlPreview: 'показать html',
        catalog: 'каталог',
        github: 'исходный код',
      },
      titleItem: {
        h1: 'Заголовок 1го ур-ня',
        h2: 'Заголовок 2го ур-ня',
        h3: 'Заголовок 3го ур-ня',
        h4: 'Заголовок 4го ур-ня',
        h5: 'Заголовок 5го ур-ня',
        h6: 'Заголовок 6го ур-ня',
      },
      imgTitleItem: {
        link: 'Добавить ссылку на изображение',
        upload: 'Загрузить изображение',
        clip2upload: 'Прикрепить изображение',
      },
      linkModalTips: {
        linkTitle: 'Добавить ссылку',
        imageTitle: 'Добавить изображение',
        descLabel: 'Описание:',
        descLabelPlaceHolder: 'Введите описание...',
        urlLabel: 'Ссылка:',
        urlLabelPlaceHolder: 'Введите ссылку...',
        buttonOK: 'OK',
      },
      clipModalTips: {
        title: 'Обрезать изображение',
        buttonUpload: 'Загрузить',
      },
      copyCode: {
        text: 'Скопировать',
        successTips: 'Скопированно!',
        failTips: 'Не удалось скопировать!',
      },
      mermaid: {
        flow: 'flow',
        sequence: 'sequence',
        gantt: 'gantt',
        class: 'class',
        state: 'state',
        pie: 'pie',
        relationship: 'relationship',
        journey: 'journey',
      },
      katex: {
        inline: 'inline',
        block: 'block',
      },
      footer: {
        markdownTotal: 'Кол-во символов',
        scrollAuto: 'Синхронизировать превью',
      },
    },
  },
}

export const EXCLUDE_TOOLBARS: ToolbarNames[] = [
  'github',
  'image',
  'mermaid',
  'katex',
  'sub',
  'sup',
  'pageFullscreen',
  'catalog',
  'htmlPreview',
]
